# Generated by Django 5.2.5 on 2025-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
