# Generated by Django 5.2.5 on 2025-10-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_condition_listing_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
