# Generated by Django 5.2.6 on 2025-11-10 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_chat_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='flagged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
