# Generated by Django 5.2.6 on 2025-11-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_listing_flagged_listing_flagged_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='flagged',
        ),
    ]
