# Generated by Django 5.2.5 on 2025-11-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_listing_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('clothes', 'Clothes'), ('makeup', 'Makeup'), ('books', 'Books'), ('toys', 'Toys'), ('tools', 'Tools'), ('vehicles', 'Vehicles'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='giving_away',
            field=models.ManyToManyField(blank=True, related_name='giving_away', to='marketplace.listingcategory'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='looking_for',
            field=models.ManyToManyField(blank=True, related_name='looking_for', to='marketplace.listingcategory'),
        ),
    ]
