# Generated by Django 5.2.7 on 2025-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_populate_listing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('flagged', 'Flagged')], default='available', max_length=20),
        ),
    ]
