# Generated by Django 5.2.5 on 2025-11-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_customuser_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
