# Generated by Django 5.2.5 on 2025-11-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_customuser_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='giving_away',
            field=models.ManyToManyField(blank=True, null=True, related_name='giving_away', to='marketplace.listingcategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='looking_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='looking_for', to='marketplace.listingcategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]