# Generated by Django 5.2.5 on 2025-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_customuser_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='giving_away',
            field=models.ManyToManyField(blank=True, related_name='giving_away', to='marketplace.listingcategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='looking_for',
            field=models.ManyToManyField(blank=True, related_name='looking_for', to='marketplace.listingcategory'),
        ),
    ]