# Generated by Django 5.2.5 on 2025-11-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_customuser_giving_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_complete',
            field=models.BooleanField(default=True, null=True),
        ),
    ]