# Generated by Django 5.2.5 on 2025-11-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_listing_status'),
        ('marketplace', '0018_customuser_onboarding_complete'),
    ]

    operations = [
    ]