# Generated by Django 5.2.5 on 2025-11-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AddField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]