# Generated by Django 5.2.5 on 2025-11-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_remove_listing_status_listing_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]