# Generated by Django 5.2.5 on 2025-11-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_chat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
