# Generated by Django 5.2.5 on 2025-11-16 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_customuser_is_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.listing'),
        ),
    ]
