# Generated by Django 5.2.5 on 2025-11-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_chat_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='custom_chat_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
