# Generated by Django 5.2.5 on 2025-11-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_chat_custom_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='custom_chat_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
