# Generated by Django 5.2.7 on 2025-11-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_notification'),
        ('marketplace', '0026_chat_custom_chat_name'),
    ]

    operations = [
    ]
