# Generated by Django 5.2.5 on 2025-11-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_remove_chat_custom_chat_name_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_custom_chat',
            field=models.BooleanField(default=False),
        ),
    ]
