# Generated by Django 5.2.6 on 2025-11-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_chat_is_custom_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to everyone'), ('logged_in', 'Only visible to logged in users')], default='public', max_length=20),
        ),
    ]
