# Generated by Django 5.2.5 on 2025-11-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_merge_0025_notification_0026_chat_custom_chat_name'),
        ('marketplace', '0029_listing_visibility'),
    ]

    operations = [
    ]
