# Generated by Django 5.2.5 on 2025-11-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_merge_20251122_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('item_request', 'Item Request Received'), ('request_approved', 'Request Approved'), ('request_canceled', 'Request Canceled'), ('request_status_change', 'Request Status Changed'), ('new_message', 'New Message in Chat'), ('suspension', 'Account Suspension'), ('custom_chat_invite', 'Added to Custom Chat')], max_length=50),
        ),
    ]
