# Generated by Django 5.2.5 on 2025-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_chat_accepted_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='noimg', upload_to='listings/'),
            preserve_default=False,
        ),
    ]
